name: notify

on:
  schedule:
    - cron: '0 23 * * 0-4'
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: install requests
        run: pip install requests
      - name: API接続テスト
        run: python test_connection.py
